# Generated by Django 5.2.6 on 2025-09-20 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farmer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True)),
                ("village", models.CharField(blank=True, max_length=255)),
                ("taluka_block", models.CharField(blank=True, max_length=255)),
                ("district", models.CharField(blank=True, max_length=255)),
                ("contact_no", models.CharField(blank=True, max_length=32)),
                ("education", models.CharField(blank=True, max_length=255)),
                ("caste_religion", models.CharField(blank=True, max_length=255)),
                (
                    "farming_experience_years",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "altitude",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                ("family_males", models.IntegerField(blank=True, null=True)),
                ("family_females", models.IntegerField(blank=True, null=True)),
                ("family_children", models.IntegerField(blank=True, null=True)),
                ("family_adult", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "farmers",
            },
        ),
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enterprise_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enterprise_type", models.CharField(max_length=255)),
                ("number", models.IntegerField(blank=True, null=True)),
                (
                    "production",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "home_consumption",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "sold_market",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "market_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enterprises",
                        to="pmksy.farmer",
                    ),
                ),
            ],
            options={
                "db_table": "enterprises",
            },
        ),
        migrations.CreateModel(
            name="CropHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop_hist_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("crop_name", models.CharField(max_length=255)),
                ("variety", models.CharField(blank=True, max_length=255)),
                ("season", models.CharField(blank=True, max_length=255)),
                (
                    "area_ha",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "production_kg",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "sold_market_kg",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "retained_seed_kg",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "home_consumption_kg",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crop_history",
                        to="pmksy.farmer",
                    ),
                ),
            ],
            options={
                "db_table": "crop_history",
            },
        ),
        migrations.CreateModel(
            name="CostOfCultivation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cost_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("crop_name", models.CharField(max_length=255)),
                ("particular", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "cost_rs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cultivation_costs",
                        to="pmksy.farmer",
                    ),
                ),
            ],
            options={
                "db_table": "cost_of_cultivation",
            },
        ),
        migrations.CreateModel(
            name="ConsumptionPattern",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cp_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("crop", models.CharField(max_length=255)),
                ("crop_product", models.CharField(blank=True, max_length=255)),
                (
                    "consumption_kg_month",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("purchased", models.BooleanField(blank=True, null=True)),
                ("pds", models.BooleanField(blank=True, null=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumption_patterns",
                        to="pmksy.farmer",
                    ),
                ),
            ],
            options={
                "db_table": "consumption_pattern",
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("years_owned", models.IntegerField(blank=True, null=True)),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="pmksy.farmer",
                    ),
                ),
            ],
            options={
                "db_table": "assets",
            },
        ),
        migrations.CreateModel(
            name="AnnualFamilyIncome",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "afi_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source", models.CharField(max_length=255)),
                (
                    "income_rs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("employment_days", models.IntegerField(blank=True, null=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annual_family_income",
                        to="pmksy.farmer",
                    ),
                ),
            ],
            options={
                "db_table": "annual_family_income",
            },
        ),
        migrations.CreateModel(
            name="AdaptationStrategy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "strategy_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("strategy", models.CharField(max_length=255)),
                ("aware", models.BooleanField(blank=True, null=True)),
                ("adopted", models.BooleanField(blank=True, null=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adaptation_strategies",
                        to="pmksy.farmer",
                    ),
                ),
            ],
            options={
                "db_table": "adaptation_strategies",
            },
        ),
        migrations.CreateModel(
            name="Financial",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fin_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("loan", models.BooleanField(blank=True, null=True)),
                ("loan_purpose", models.CharField(blank=True, max_length=255)),
                ("credit_returned", models.BooleanField(blank=True, null=True)),
                ("kcc", models.BooleanField(blank=True, null=True)),
                ("kcc_used", models.BooleanField(blank=True, null=True)),
                ("memberships", models.JSONField(blank=True, null=True)),
                ("benefits", models.TextField(blank=True)),
                ("soil_testing", models.BooleanField(blank=True, null=True)),
                ("training", models.TextField(blank=True)),
                ("info_sources", models.TextField(blank=True)),
                ("constraints", models.TextField(blank=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financials",
                        to="pmksy.farmer",
                    ),
                ),
            ],
            options={
                "db_table": "financials",
            },
        ),
        migrations.CreateModel(
            name="IncomeCrop",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "income_crop_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("season", models.CharField(blank=True, max_length=255)),
                ("crop_name", models.CharField(max_length=255)),
                (
                    "production_qntl",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "yield_qntl_ha",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "price_rs_qntl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "gross_income_rs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "byproduct_income_rs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_crops",
                        to="pmksy.farmer",
                    ),
                ),
            ],
            options={
                "db_table": "income_crops",
            },
        ),
        migrations.CreateModel(
            name="IrrigatedRainfed",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ir_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("crop", models.CharField(max_length=255)),
                ("sowing_date", models.DateField(blank=True, null=True)),
                ("harvesting_date", models.DateField(blank=True, null=True)),
                (
                    "rainfed_area",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "irrigated_area",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "fertilizer_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irrigated_rainfed",
                        to="pmksy.farmer",
                    ),
                ),
            ],
            options={
                "db_table": "irrigated_rainfed",
            },
        ),
        migrations.CreateModel(
            name="LandHolding",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "land_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=255)),
                (
                    "total_area_ha",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "irrigated_area_ha",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("irrigation_source", models.CharField(blank=True, max_length=255)),
                ("irrigation_no", models.CharField(blank=True, max_length=255)),
                (
                    "irrigation_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "irrigation_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("soil_details", models.TextField(blank=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="land_holdings",
                        to="pmksy.farmer",
                    ),
                ),
            ],
            options={
                "db_table": "land_holdings",
            },
        ),
        migrations.CreateModel(
            name="MarketPrice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "price_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("crop", models.CharField(max_length=255)),
                ("season", models.CharField(blank=True, max_length=255)),
                (
                    "area_ha",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "production_tons",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "price_rs_qntl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_prices",
                        to="pmksy.farmer",
                    ),
                ),
            ],
            options={
                "db_table": "market_price",
            },
        ),
        migrations.CreateModel(
            name="Migration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "migration_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("age_gender", models.CharField(blank=True, max_length=255)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("migration_type", models.CharField(blank=True, max_length=255)),
                (
                    "remittance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="migration_records",
                        to="pmksy.farmer",
                    ),
                ),
            ],
            options={
                "db_table": "migration",
            },
        ),
        migrations.CreateModel(
            name="NutrientManagement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nutrient_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("season", models.CharField(blank=True, max_length=255)),
                ("crop_name", models.CharField(blank=True, max_length=255)),
                (
                    "fym_kg",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "nitrogen_kg",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "phosphate_kg",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "gromer_kg",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("other_fertilizer", models.CharField(blank=True, max_length=255)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrient_management",
                        to="pmksy.farmer",
                    ),
                ),
            ],
            options={
                "db_table": "nutrient_management",
            },
        ),
        migrations.CreateModel(
            name="PestDisease",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pest_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("season", models.CharField(blank=True, max_length=255)),
                ("pest_disease", models.CharField(max_length=255)),
                ("chemical_used", models.CharField(blank=True, max_length=255)),
                (
                    "chemical_qty",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "chemical_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "labour_days",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "labour_charge",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pest_diseases",
                        to="pmksy.farmer",
                    ),
                ),
            ],
            options={
                "db_table": "pest_disease",
            },
        ),
        migrations.CreateModel(
            name="WaterManagement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wm_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("season", models.CharField(blank=True, max_length=255)),
                ("irrigation_source", models.CharField(blank=True, max_length=255)),
                ("irrigation_count", models.IntegerField(blank=True, null=True)),
                (
                    "depth",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "energy_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "labour_charge",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_management",
                        to="pmksy.farmer",
                    ),
                ),
            ],
            options={
                "db_table": "water_management",
            },
        ),
        migrations.CreateModel(
            name="Weed",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weed_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("season", models.CharField(blank=True, max_length=255)),
                ("weed_type", models.CharField(blank=True, max_length=255)),
                ("weeding_time", models.CharField(blank=True, max_length=255)),
                ("herbicide", models.CharField(blank=True, max_length=255)),
                (
                    "chemical_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "labour_days",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "labour_charge",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weeds",
                        to="pmksy.farmer",
                    ),
                ),
            ],
            options={
                "db_table": "weeds",
            },
        ),
    ]
