# Generated by Django 5.2.6 on 2025-09-23 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_wizard", "0003_alter_run_options"),
        ("pmksy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportRecordLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.TextField()),
                (
                    "record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pmksy_label",
                        to="data_wizard.record",
                    ),
                ),
            ],
            options={
                "verbose_name": "import record label",
                "verbose_name_plural": "import record labels",
            },
        ),
    ]
