# Generated by Django 5.2.6 on 2025-09-23 08:16

import uuid

import pmksy.models
from django.db import migrations, models
from django.db.models import Q


def populate_registration_ids(apps, schema_editor):
    Farmer = apps.get_model("pmksy", "Farmer")
    registration_filter = Q(registration_id__isnull=True) | Q(registration_id="")

    for farmer in Farmer.objects.filter(registration_filter).iterator():
        farmer.registration_id = uuid.uuid4().hex
        farmer.save(update_fields=["registration_id"])


def clear_registration_ids(apps, schema_editor):
    Farmer = apps.get_model("pmksy", "Farmer")
    Farmer.objects.update(registration_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("pmksy", "0002_importrecordlabel"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="registration_id",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(populate_registration_ids, clear_registration_ids),
        migrations.AlterField(
            model_name="farmer",
            name="registration_id",
            field=models.CharField(
                blank=True,
                default=pmksy.models.generate_registration_id,
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
