# Generated by Django 5.2.6 on 2025-09-23 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_wizard", "0003_alter_run_options"),
        ("pmksy", "0003_farmer_registration_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportRunMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sheet_name", models.CharField(blank=True, max_length=255)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pmksy_metadata",
                        to="data_wizard.run",
                    ),
                ),
            ],
            options={
                "verbose_name": "import run metadata",
                "verbose_name_plural": "import run metadata",
                "db_table": "pmksy_import_run_metadata",
            },
        ),
    ]
