# Generated by Django 5.2.6 on 2025-09-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pmksy", "0004_importrunmetadata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consumptionpattern",
            old_name="crop",
            new_name="commodity",
        ),
        migrations.RenameField(
            model_name="nutrientmanagement",
            old_name="fym_kg",
            new_name="fym_compost_kg_ha",
        ),
        migrations.RenameField(
            model_name="nutrientmanagement",
            old_name="gromer_kg",
            new_name="mop_kg_ha",
        ),
        migrations.RenameField(
            model_name="nutrientmanagement",
            old_name="nitrogen_kg",
            new_name="urea_kg_ha",
        ),
        migrations.RemoveField(
            model_name="consumptionpattern",
            name="consumption_kg_month",
        ),
        migrations.RemoveField(
            model_name="consumptionpattern",
            name="crop_product",
        ),
        migrations.RemoveField(
            model_name="consumptionpattern",
            name="pds",
        ),
        migrations.RemoveField(
            model_name="consumptionpattern",
            name="purchased",
        ),
        migrations.RemoveField(
            model_name="nutrientmanagement",
            name="other_fertilizer",
        ),
        migrations.RemoveField(
            model_name="nutrientmanagement",
            name="phosphate_kg",
        ),
        migrations.AddField(
            model_name="adaptationstrategy",
            name="strategy_order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consumptionpattern",
            name="food_expenditure_rs_month",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="consumptionpattern",
            name="other_source_qty",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="consumptionpattern",
            name="purchased_from_market_qty",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="consumptionpattern",
            name="through_pds_qty",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="consumptionpattern",
            name="unit",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="farmer",
            name="survey_serial_number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="financial",
            name="additional_constraints",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="financial",
            name="cold_storage_facilities",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financial",
            name="cooperative_marketing_society",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financial",
            name="direct_marketing_mode",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financial",
            name="distance_to_market_km",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="financial",
            name="market_availability",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financial",
            name="membership_cooperative",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financial",
            name="membership_fpo",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financial",
            name="membership_marketing",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financial",
            name="membership_shg",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financial",
            name="membership_useful",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financial",
            name="road_connectivity",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financial",
            name="sell_to_government_msp",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financial",
            name="soil_erosion_problem",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financial",
            name="transportation_facilities",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financial",
            name="wild_animal_problem",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importrunmetadata",
            name="column_mappings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="importrunmetadata",
            name="data_start_row_index",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="importrunmetadata",
            name="header_row_index",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importrunmetadata",
            name="loader_options",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="landholding",
            name="cultivated_area_ha",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="landholding",
            name="soil_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="landholding",
            name="waste_land_area_ha",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="migration",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migration",
            name="gender",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="migration",
            name="income_contribution_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="migration",
            name="members_migrated",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nutrientmanagement",
            name="dap_kg_ha",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="nutrientmanagement",
            name="other_fertilizer_kg_ha",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="watermanagement",
            name="farm_pond_available",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="watermanagement",
            name="water_availability",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
